name: Cache Demo

on: [push]

jobs:
  demo:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: prime-cache-5bcf949
      id: prime-cache-5bcf949
      uses: actions/cache@v4
      with:
        key: cache-5bcf949
        path: ~/.npm
        
    - name: Install dependencies
      run: npm ci
      
    - name: Show cache result
      run: echo "Cache hit: ${{ steps.prime-cache-5bcf949.outputs.cache-hit }}"
