name: Cache Demo

on: [push]

jobs:
  demo:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: prime-cache-5bcf949
      id: prime-cache-5bcf949
      uses: actions/cache@v4
      with:
        key: cache-5bcf949
        path: ~/.npm
        
    - run: npm ci
